[project]
name = "sparkcityx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "pknight", email = "paul.knight@delmarvacomputer.com" }
]
requires-python = ">=3.13,<3.15"
dependencies = [
    "altair>=5,<7",
    "fastparquet>=2026.5.0",
    "pandas>=2.2,<3",
    "psycopg[binary]>=3.2,<4",
    "pyarrow>=25.0.1",
    "pyspark>=4.2,<4.3",
    "python-dotenv>=1.1,<2",
    "streamlit>=1.64,<2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "pytest>=8.3,<10",
    "seaborn>=0.13.2",
]

[project.scripts]
sparkcityx = "sparkcityx:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
