spark.app.name                         SmartCityIoTPipeline
spark.master                           spark://spark-master:7077
spark.driver.host                      jupyter
spark.driver.bindAddress               0.0.0.0
spark.driver.memory                    2g
spark.executor.memory                  2g
spark.executor.cores                   2
spark.sql.adaptive.enabled             true
spark.sql.adaptive.coalescePartitions.enabled true
spark.sql.session.timeZone             UTC
spark.sql.shuffle.partitions           8
spark.jars.packages                    org.postgresql:postgresql:42.5.0

